# Generated by Django 3.1.4 on 2021-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='documents/')),
                ('judul', models.CharField(max_length=50, null=True)),
                ('caption', models.TextField(null=True)),
            ],
        ),
    ]
