# Generated by Django 3.1.4 on 2021-06-06 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210606_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
